export const items = [
  {
    id: Math.random(),
    title: "وجبة فطور ملكية",
    description: "فطور غني بالمكونات الصحية مثل البيض والعسل مع الخبز الطازج.",
    price: "65 جنيه",
    category: "فطور",
    imgUrl: "01.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة كريب لذيذة",
    description: "كريب محشو بالشوكولاتة أو الجبن حسب اختيارك.",
    price: "40 جنيه",
    category: "فطور",
    imgUrl: "02.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء إيطالية",
    description: "بيتزا مارغريتا مع طبق جانبي من الباستا.",
    price: "150 جنيه",
    category: "غداء",
    imgUrl: "03.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة كبسة دجاج",
    description: "أرز مع خلطة الكبسة الشهية والدجاج المشوي.",
    price: "130 جنيه",
    category: "غداء",
    imgUrl: "04.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة شاورما شامية",
    description: "شاورما لحم أو دجاج مع صوصات لذيذة وخبز طازج.",
    price: "90 جنيه",
    category: "عشاء",
    imgUrl: "05.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة برجر كلاسيك",
    description: "برجر مشوي مع الجبن والخس والطماطم والبطاطس المقلية.",
    price: "75 جنيه",
    category: "عشاء",
    imgUrl: "06.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة مقبلات شرقية",
    description: "تشكيلة من الحمص والمتبل مع الخبز العربي الطازج.",
    price: "45 جنيه",
    category: "مقبلات",
    imgUrl: "07.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة وجبات خفيفة",
    description: "مزيج من المكسرات والفواكه المجففة اللذيذة.",
    price: "30 جنيه",
    category: "وجبات خفيفة",
    imgUrl: "08.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة بان كيك بالعسل",
    description: "بان كيك طري مغطى بالعسل والمكسرات.",
    price: "50 جنيه",
    category: "تحلية",
    imgUrl: "09.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة آيس كريم فواكه",
    description: "آيس كريم بنكهات الفواكه الطازجة مع صوص الشوكولاتة.",
    price: "35 جنيه",
    category: "تحلية",
    imgUrl: "10.jpg",
  },
];
